customhost = "employee.c9dppnowgqw3.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "kennethkeanemordon-employee"
customregion = "us-east-1"
